global using Application.Services.Interfaces;
global using Application.Services.S3Handlers.Auth;
global using Application.Services.S3Handlers.Buckets;
global using Application.Services.S3Handlers.Objects;
global using Application.Services.S3Handlers.Settings;
global using Domain.Common;
global using Domain.Entities;
global using Infrastructure.Services;
global using Microsoft.AspNetCore.DataProtection.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using S3ServerLibrary;
global using Object = Domain.Entities.Object;